### ISSUE TITLE
update packages to newer versions

### ISSUE THREAD

**Issue by salimdellali** [ErickWendel/generic-repository-nodejs-typescript-article#2]
It's been a while since this project was built, I was trying to follow along your [Medium post](https://medium.com/@erickwendel/generic-repository-with-typescript-and-node-js-731c10a1b98e) but my typescript is complaining about `InsertOneWriteOpResult` as it can't find it in `mongodb`

my packages in `package.json` at the time of writing this issue are:
```json
"dependencies": {
    "@types/mongodb": "^4.0.7",
    "mongodb": "^4.6.0"
  }
```

the sure thing is if I install the packages as described in the `package.json` of this project, everything works fine, but I guess a lot of beginners following along the tutorial in the [Medium post](https://medium.com/@erickwendel/generic-repository-with-typescript-and-node-js-731c10a1b98e) will probably install the latest versions of `mongodb` and `@types/mongodb`

Please bump the packages to latest versions and make the necessary changes. Thank's in advance

**Comment by ErickWendel** [comment]
Hey @salimdellali thanks for the feedback. Would you open a PR with those changes?

**Comment by salimdellali** [comment]
@ErickWendel PR created

**Comment by ErickWendel** [comment]
Thanks!!
